### ISSUE TITLE
Top-level await

### ISSUE THREAD

**Issue by Yzrsah** [gzzhanghao/eslint-plugin-await-in-async#1]
Hi! Thanks for your plugin.

It's not possible to use this plugin with top level await.
Since I use top level await I had to disable eslint-plugin-await-in-async.

https://babeljs.io/docs/en/babel-plugin-syntax-top-level-await

**Comment by gzzhanghao** [comment]
`topLevelAwait` option added in v0.1.2

**Comment by Yzrsah** [comment]
Thank you 👍 😊
